### check server status
GET http://localhost:8000

# ======= Admin API
### post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
   
    "fName": "Anmol",
    "lName": "Bhattarai",
    "email": "annnR@gmail.com",
    "password": "anmolll",
    "phone": "0444333444",
    "address": "Queanbeyan",
    "dob": "1995-01-16"


}
### post new admin user
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
   
    "email": "bsal@gmail.com",
    "password": "aaaa"


}


###category apis

###post the categoey
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
"status": "active",
"name": "desktop",
"parentId": ""

}

### get categories
GET http://localhost:8000/api/v1/category
