### check server status
GET http://localhost:8000

# ======= Admin API
### post new admin user
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
   
    "fName": "Anmol",
    "lName": "Bhattarai",
    "email": "annn@gmail.com",
    "password": "anmolll",
    "phone": "0444333444",
    "address": "Queanbeyan",
    "dob": "1995-01-16"


}
### post new admin user
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
   
    "email": "bsal@gmail.com",
    "password": "aaaa"


}

